[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet Charity_Fundraising_DBMS.dll"
restartPolicyType = "on_failure"

[env]
ASPNETCORE_ENVIRONMENT = "Development"
DB_SERVER = "${{ services.charitydb.host }}"
DB_NAME = "${{ services.charitydb.database_name }}"
DB_USER = "${{ services.charitydb.username }}"
DB_PASSWORD = "${{ services.charitydb.password }}"
TrustServerCertificate = "true"
ConnectionRetryCount = "10"
ConnectionRetryDelay = "10"
