on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      charity-fundraising-api:
        image: docker
        env:
          ASPNETCORE_ENVIRONMENT: Development
          DB_SERVER: charitydb
          DB_NAME: Charity_Fundraising_DBMS
          DB_USER: sa
          DB_PASSWORD: NomANRIAZ@90
          TrustServerCertificate: true
        options: --health-cmd "curl --fail http://localhost:80/ || exit 1" --health-interval 1m --health-timeout 10s --health-retries 3